### ISSUE TITLE
Error when switching a layer to edit mode

### ISSUE THREAD

**Issue by haubourg** [iona5/coordinator#3]
Hi, very nice tool @iona5 !

I'a having one issue when switching to edit mode:

```
AttributeError: type object 'CaptureMode' has no attribute 'CapturePoint' 
Traceback (most recent call last):
  File "/home/regis/OSLANDIA/support/gendarmerie_stsi2/profil_dev/profiles/default/python/plugins/coordinator/coordinator.py", line 422, in mapToolChanged
    self.dockwidget.addFeatureButton.setEnabled(self.__checkEnableAddFeatureButton())
  File "/home/regis/OSLANDIA/support/gendarmerie_stsi2/profil_dev/profiles/default/python/plugins/coordinator/coordinator.py", line 165, in __checkEnableAddFeatureButton
    shouldEnable = bool(self.dockwidget.hasInput() and self.__compatibleMapTool())
  File "/home/regis/OSLANDIA/support/gendarmerie_stsi2/profil_dev/profiles/default/python/plugins/coordinator/coordinator.py", line 174, in __compatibleMapTool
    if(newTool.mode() == QgsMapToolCapture.CaptureMode.CapturePoint
AttributeError: type object 'CaptureMode' has no attribute 'CapturePoint'
Version de Python : 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0] 
Version de QGIS : 3.4.11-Madeira Madeira, 9a8a6d4687 
```
Regards

**Comment by iona5** [comment]
Hi

thanks for the report, i will look into it. the error is kinda odd though, unless QGIS made some unexpected changes under the hood. 

thanks again
Jonas

**Comment by iona5** [comment]
Hm, cannot reproduce on 3.4.12 and 3.8.3

can you tell me what version did you install (OS, installation method/packages eg. OSGEO4 or windows installer)?

Also, if you open up  the Plugins->Python Console, what is the output if you enter

    type(qgis.gui.QgsMapToolCapture) 

and

    QgsMapToolCapture.CaptureMode.CapturePoint

?

thanks!

**Comment by haubourg** [comment]
Hi @iona5 

I test it on Ubuntu 18.04 with self compiled versions. I have the very same errors with QGIS master, or release (Zanzibar 3.8.2) 

 QGIS | 3.4.11-Madeira |  | 9a8a6d4687
-- | -- | -- | --
Qt | 5.9.5 | 
GDAL/OGR | 2.4.2 | 
GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Version du client PostgreSQL | 11.5 (Ubuntu 11.5-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.2
Version de PROJ.4 : | 520



> type(qgis.gui.QgsMapToolCapture)

```
type(qgis.gui.QgsMapToolCapture) 
<class 'sip.wrappertype'>
```
```

>>> from coordinator import * 
>>> QgsMapToolCapture.CaptureMode.CapturePoint
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: type object 'CaptureMode' has no attribute 'CapturePoint'
```

**Comment by iona5** [comment]
hey thank you very much. still not quite clear what the underlying problem is but i noticed you are using Qt 5.9, maybe the enum-types are handled differently there... I use the current OS4GEO install, where QgsMapToolCapture.CaptureMode is a sip.enumtype object while yours is simply a "type" object.

anyway, i would be very glad if you find the time to try the following two solutions, both replacing lines 174-176 in `plugins/coordinator/coordinator.py` from
```
            if(newTool.mode() == QgsMapToolCapture.CaptureMode.CapturePoint
                or newTool.mode() == QgsMapToolCapture.CaptureMode.CapturePolygon
                or newTool.mode() == QgsMapToolCapture.CaptureMode.CaptureLine
```
to:

**Solution 1:** (please try that first)

```
            if(newTool.mode() == QgsMapToolCapture.CapturePoint
                or newTool.mode() == QgsMapToolCapture.CapturePolygon
                or newTool.mode() == QgsMapToolCapture.CaptureLine
```
(removing the `.CaptureMode` in between)

if this doesnt work please use

**Solution 2**

```
            if(newTool.mode() == 1
                or newTool.mode() == 3
                or newTool.mode() == 2
```
which should work in any case

please let me now what prevents the error.

thank you!

changes as diffs:
[coordinator_bug003_solution1.patch.txt](https://github.com/iona5/coordinator/files/3675642/coordinator_bug003_solution1.patch.txt)
[coordinator_bug003_solution2.patch.txt](https://github.com/iona5/coordinator/files/3675641/coordinator_bug003_solution2.patch.txt)
